[package]
name = "glitter"
version = "0.1.1"
authors = [":kelko:"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7"
clap = "3.2"
yaml-rust = "0.4"
exitcode = "1.1.2"
