[package]
name = "glitter"
version = "0.1.0"
authors = [":kelko:"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = { version = "0.6.10" }
clap = "2.33.0"
yaml-rust = "0.4"
exitcode = "1.1.2"
